FROM ubuntu:latest

# Install necessary dependencies
RUN apt-get update \
    && apt-get install -y build-essential g++ openjdk-8-jdk python3 python3-pip time\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy the contents of the current directory to the working directory
COPY . .

# Make run.sh executable
RUN chmod +x ./run.sh

# Specify the default command with placeholder arguments
ENTRYPOINT ["./run.sh"]


